on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: miktex/miktex
    steps:
    - name: build pdf
      uses: actions/checkout@v3
    - name: run docker command miktex
      run: |
            pdflatex main.tex
    - name: Archive pdf file
      uses: actions/upload-artifact@v3
      with:
        name: PDF file
        path: ./main.pdf