on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: miktex/miktex
    steps:
    - name: build pdf
      uses: actions/checkout@v3
    - name: run docker command miktex
      run: |
            docker run --rm -ti \
            -v miktex:/miktex/.miktex \
            -v $(pwd):/miktex/work \
            -e MIKTEX_GID=$(id -g) \
            -e MIKTEX_UID=$(id -u) \
            miktex/miktex \
            pdflatex main.tex
    - name: Archive pdf file
      uses: actions/upload-artifact@v3
      with:
        name: PDF file
        path: ./main.pdf